### PR TITLE
Update isort to version >=5.0

### LINKED ISSUE #52: Module 'isort.settings' has no attribute 'from_path'
```
>>> ff -c
Running black on 3 files...
All done! ✨ � ✨
3 files left unchanged.
Traceback (most recent call last):
  File "W:\Miniconda3\envs\cg_playground-py36\Scripts\ff-script.py", line 9, in <module>
    sys.exit(main())
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\esss_fix_format\cli.py", line 218, in main
    return _main(files_or_directories, check, stdin, commit, format_code, verbose=verbose)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\esss_fix_format\cli.py", line 451, in _main
    changed, new_errors, formatter = _process_file(filename, check, pydevf_format_func,
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\esss_fix_format\cli.py", line 316, in _process_file
    settings_loaded = isort.settings.from_path(settings_path)
AttributeError: module 'isort.settings' has no attribute 'from_path'
```
We should either conform to the current `isort` version or update `isort` version on `environment.devenv.yml` to 
`isort>=4.3.4, <5.0`

### PR DESCRIPTION
**Pull request by gcardozo123**
`isort>=4.3.4` was one of the dependencies which caused
`esss_fix_format` environment to download `isort` most recent
version (at this moment `5.3.2`). Since `isort 5` breaks compatibility
with 4 we need to update `esss_fix_format`.

For more info on changes when upgrading from `isort` 4 to 5 see:
https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/

This fixes #52

### CODE REVIEW

**Comment by gcardozo123** [comment]
> LGTM, just please update the CHANGELOG as well

I'm not sure if this should be a minor release because it's a bug fix or a major release because `known_standard_library` became `extra_standard_library`, so `esss_fix_format` users will need to update their `.isort.cfg`. What do you say?

**Comment by nicoddemus** [comment]
It is a major release actually, because we know only support isort>5.
